language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator10.0
script:
- set -o pipefail
- travis_retry xcodebuild -workspace BeyovaNet.xcworkspace -scheme "BeyovaNet iOS" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
- travis_retry xcodebuild -workspace BeyovaNet.xcworkspace -scheme "BeyovaNet macOS" build-for-testing test | xcpretty

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - git submodule update --init --recursive